app/models.py
from . import db



class Vote(db.Model):
    __tablename__='votes'
    id = db.Column(db.Integer, primary_key=True)
    product = db.Column(db.String(60))


class CapWeight(db.Model):
    __tablename__='capweight'
    id = db.Column(db.Integer, primary_key=True)
    capacity = db.Column(db.Integer)

class ItemWeight(db.Model):
    __tablename__='itemweight'
    id = db.Column(db.Integer, primary_key=True)
    item = db.Column(db.Integer)

app/__init__.py
from flask import Flask
from config import config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()
bootstrap=Bootstrap()


def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config[config_name])
    from .majority import majority as majority_blueprint
    app.register_blueprint(majority_blueprint)
    from .calculator import calculator as calculator_blueprint
    app.register_blueprint(calculator_blueprint)
    bootstrap.init_app(app)
    db.init_app(app)
    return app

app/calculator/__init__.py
from flask import Blueprint

calculator = Blueprint('calculator', __name__, )
from . import routes

app/calculator/routes.py
from . import calculator
from .cargo import optimal_weight
from app import db
from flask import render_template, request, flash, redirect, url_for
from ..models import db, CapWeight, ItemWeight

@calculator.route('/calculator')
def index():
    return render_template('calculator/calculator.html')

@calculator.route('/calculator/new')
def new_calculator():
    db.session.query(CapWeight.capacity).delete()
    db.session.query(ItemWeight.item).delete()
    db.session.commit()
    return render_template('calculator/calculator.html')

@calculator.route('/calculator/add_capacity', methods=['POST', 'GET'])
def add_capacity():
    capacity = request.form.get('capacity', type=int)
    if request.method == 'POST' and capacity is not None:
        db.session.query(CapWeight.capacity).delete()
        entry = CapWeight(capacity=capacity)
        db.session.add(entry)
        db.session.commit()
        flash("Your maximum loading capacity is " + str(capacity))
    else:
        flash('Please enter a valid number')
        return redirect(url_for('calculator.index')) #in case if user refreshes browser. It's called post-redirect-get pattern
    return redirect(url_for('calculator.index')) #should be 'show_result'

@calculator.route('/calculator/add_item', methods=['POST', 'GET'])
def add_item():
    item = request.form.get('item', type=int)
    if request.method == 'POST' and item is not None:
        entry = ItemWeight(item=item)
        db.session.add(entry)
        db.session.commit()
        #flash("You've added " + str(item))
    else:
        flash('Please enter a valid number')
        return redirect(url_for('calculator.index')) #in case if user refreshes browser. It's called post-redirect-get pattern
    return redirect(url_for('calculator.index'))

@calculator.route('/calculator/result')
def result():
    items = ItemWeight.query.filter(ItemWeight.item).all()
    loading_capacity=CapWeight.query.filter(CapWeight.capacity).first()
    #flash('' + str(loading_capacity))
    if items !=[] and (loading_capacity is not None):
        W = loading_capacity.capacity
        array = [i.item for i in items]
        optimal = optimal_weight(W, array)
        db.session.query(CapWeight.capacity).delete()
        db.session.query(ItemWeight.item).delete()
        db.session.commit()
    else:
        flash('Please provide a valid data')
        return redirect(url_for('calculator.index'))
    return render_template('calculator/calculator.html', optimal=str(optimal))

app/majority/__init__.py
from flask import Blueprint

majority = Blueprint('majority', __name__, )
from . import routes

app/majority/routes.py
from . import majority
from .majority_count import get_majority_element
from app import db
from flask import render_template, request, flash, redirect, url_for
from ..models import Vote, db


@majority.route('/majority')
def vote():
    return render_template('majority/vote.html')


@majority.route('/new_count')
def new_count():
    db.session.query(Vote.product).delete()
    db.session.commit()
    return redirect(url_for('majority.show_result'))


@majority.route('/add', methods=['POST', 'GET'])
def add_entry():
    #db.create_all()
    try:
        if request.method =='POST':
            select=request.form['select'] # name='select' in radio buttons (voting_app.html file)
            entry=Vote(product=str(select))
            db.session.add(entry)
            db.session.commit()
            #flash("You've selected product " + select, 'product')
        else:
            return redirect(url_for('majority.vote')) #in case if user refreshes browser. It's called post-redirect-get pattern
    except:
        flash('No product was selected', 'product')
    return redirect(url_for('majority.show_result')) #should be 'show_result'

@majority.route('/result')
def show_result():
    res=Vote.query.order_by(Vote.product).all()
    array=[i.product for i in res]
    if array!=[]:
        result= get_majority_element(array, 0, len(array)-1)
    else:
        result=''
    return render_template('majority/vote.html', result=result)

app/templates/base.html
{%extends 'bootstrap/base.html'%}

{%block title%}Tanya's website{%endblock%}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='cover.css') }}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
{%endblock%}

{% block body %}
<!--<div class="container-fluid" >-->
    {% block navbar%}
        <nav class="navbar" style="top:0; position:fixed">

            <div class="navbar-nav pull-left">
                <a href="{{url_for('index')}}" class="btn" >Home </a>
            </div>
            <div class="navbar-nav pull-right">
                <a href="{{url_for('contact')}}" class="btn">Contact</a>
            </div>
        </nav>

    {%endblock%}
{%block content%}
      <!--<div class="container">-->
         <div class="site-wrapper">
             <div class="site-wrapper-inner">
             <div class="cover-container">
               <div class="inner">

                   {%block page_content%} {%endblock%}

               </div>
             </div>
             </div>
         </div>



  {%endblock%}


{%endblock%}

app/templates/calculator/calculator.html
{% extends 'base.html' %}

{% block page_content%}

<h1>Cargo Calculator</h1> <br>
<h3 class="lead">This application calculates the optimal cargo weight in order to maximise the
    number of items can be loaded onto a vehicle or a ship. It determines the optimal
    combination  of mixed weight products to utilise the maximum loading capacity. <br>All entries must be
    integer numbers and in the same units of weight (pounds, lb, kg, tonne).
</h3> <br>
    <p class="lead" style="color:#DEB887">Please enter a weight for each item one at a time.

        <form action="{{ url_for('calculator.add_item') }}" method=post id="id">
                <p><input type="text" name="item"> </p>
                <p> <input type="submit" value='Submit' ></p>
        </form>
    </p>

    <p class="lead" style="color:#DEB887"> Please enter the maximum loading capacity.

        <form action="{{ url_for('calculator.add_capacity') }}" method=post id="id">
                <p><input type="text" name="capacity"></p>
                <p ><input type=submit value=Submit ></p>
        </form>
    </p>

{% for message in get_flashed_messages() %}
      <div style="color:#FF8C00; font-size: 16px">{{ message }}</div>
  {% endfor %}

<p class="lead inner" > <a href="{{url_for('calculator.result')}}" class="btn btn-default">
    <b>Optimal Cargo Weight</b></a>
</p>


{% if optimal %}
<h4 style="color:#DEB887"> {{ optimal }} is the optimal weight </h4>
{% endif %}


   <div class="mastfoot">
        <div class="inner">
        Click <a href="{{url_for('calculator.new_calculator')}}">here</a> to start new calculation.
        </div>
    </div>
{%endblock%}

app/templates/contact.html
{%extends 'base.html'%}

{%block page_content%}

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">

          <h1 class="jumbotron" ><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span></h1>

        <p class="btn-default">+(44) 7904245026</p>
      </div>
    </div>
  </div>

   <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">

          <h1 class="jumbotron" ><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></h1>

        <p class="btn-default">tbadamshina@hotmail.com</p>
      </div>
    </div>
  </div>

    <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <div class="caption">

          <h1 class="jumbotron " ><span class=" fa fa-github " aria-hidden="true"></span></h1>

        <p class="btn-default">https://github.com/tanyaba</p>
      </div>
    </div>
  </div>
</div>

{%endblock%}

app/templates/index.html
{%extends 'base.html'%}

{%block page_content%}

        <h2 >Hi! I'm Tanya.</h2>
        <p class="lead">Below you can try my applications that are based on algorithmic techniques. </p>
               <p class="lead inner" > <a href="{{url_for('majority.vote')}}" class="btn btn-default"><b>Majority Counting</b></a></p>
               <p class="lead inner" > <a href="{{url_for('calculator.index')}}" class="btn btn-default"><b>Cargo Calculator</b></a></p>

{%endblock%}

app/templates/majority/vote.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'base.html' %}

{% block page_content%}

<h1>Majority Counting</h1> <br>
<h3 class="lead">This application counts the votes and selects the most popular product.
    A successful product should get more than half of votes.</h3> <br>
<p class="lead" style="color:#DEB887"> Please select your favorite product</p>

<div> <form action="{{ url_for('majority.add_entry') }}" method=post id="id">
            <p style="color:#DEB887">Product One <input type="radio" name="select" value="One"></p>
            <p style="color:#DEB887">Product Two <input type="radio" name="select" value="Two"></p>
            <p ><input class="btn-default" type=submit value=Submit></p>
        </form>
</div>
{% for message in get_flashed_messages(category_filter=["product"]) %}
      <div class="product">{{ message }}</div>
  {% endfor %}

{% if result %}
<h4 style="color:#DEB887">So far, Product {{ result }} is the popular choice.</h4>
{% endif %}



   <div class="mastfoot">
        <div class="inner">
        Click <a href="{{url_for('majority.new_count')}}">here</a> to start new counting.
        </div>
    </div>

{%endblock%}